import { mkdir, writeFile, cp, rm } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SHOP_URL, CONTACT_EMAIL, CONTACT_PHONE, RECIPE_SLUG, products, categories, dressingArchive } from './data.mjs';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const out = join(root, 'dist');
const basePath = process.env.SITE_BASE_PATH || '/';
if (!/^\/(?:[a-z0-9-]+\/)*$/i.test(basePath)) throw new Error('SITE_BASE_PATH must be an absolute directory path ending in /');
const publicOrigin = process.env.PUBLIC_ORIGIN || '';
if (publicOrigin && (!/^https:\/\/[a-z0-9.-]+$/i.test(publicOrigin) || new URL(publicOrigin).origin !== publicOrigin)) throw new Error('PUBLIC_ORIGIN must be an HTTPS origin');
const publicUrl = path => publicOrigin ? `${publicOrigin}${basePath}${path.replace(/^\//, '')}` : '';
const prefixLocalUrls = html => html.replace(/\b(href|src|content)="\/(?!\/)/g, (_, attribute) => `${attribute}="${basePath}`);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dimensions = file => file === 'logo-wordmark.png' ? [328,78] : file === 'logo.png' ? [400,400] : file === 'founder.webp' ? [750,500] : file.startsWith('food-') ? [1200,800] : [640,640];
const img = (file, alt, cls='', eager=false) => `<img src="/images/${esc(file)}" alt="${esc(alt)}" class="${esc(cls)}" width="${dimensions(file)[0]}" height="${dimensions(file)[1]}" decoding="async" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'}>`;
const bag = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true" focusable="false"><path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg>';
const shop = (label='Zum Shop', placement='body', cls='') => `<a class="shop-link ${cls}" href="${SHOP_URL}" data-shop-link data-shop-placement="${placement}">${bag}<span>${esc(label)}</span><span class="sr-only"> – weiter zu chelonaki.eu</span></a>`;
const link = (href,label,cls='text-link') => `<a class="${cls}" href="${href}">${esc(label)}<span aria-hidden="true"> ↗</span></a>`;
const chapter = (n,label,title) => `<div class="chapter reveal"><span class="chapter-index">${n} / ${esc(label)}</span><span class="chapter-line"></span><h2>${title}</h2></div>`;
const header = () => `<a class="skip-link" href="#inhalt">Zum Inhalt springen</a><header class="site-header"><div class="header-inner shell"><a class="brand" href="/" aria-label="O-SOME TASTE – Startseite">${img('logo-wordmark.png','O-SOME TASTE – Be the Difference!','brand-logo',true)}</a><nav class="desktop-nav" aria-label="Hauptnavigation"><a href="/collections/all">Produkte</a><a href="/pages/rezepte">Rezepte & Ideen</a><a href="/pages/uber-uns">Über uns</a><details class="business-menu"><summary>Für Unternehmen</summary><div class="business-dropdown"><a href="/pages/geschaftskunden">Geschäftskunden</a><a href="/pages/private-label">Private Label</a></div></details><a href="/pages/contact">Kontakt</a></nav><div class="header-actions">${shop('Shop','header','header-shop')}<details class="mobile-menu" data-mobile-menu><summary>Menü <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile Navigation"><a href="/collections/all">Produkte</a><a href="/pages/rezepte">Rezepte & Ideen</a><a href="/pages/uber-uns">Über uns</a><a href="/pages/geschaftskunden">Geschäftskunden</a><a href="/pages/private-label">Private Label</a><a href="/pages/contact">Kontakt</a></nav></details></div></div></header>`;
const footer = () => `<footer class="site-footer"><div class="shell footer-grid"><div class="footer-brand">${img('logo-wordmark.png','O-SOME TASTE – Be the Difference!','footer-logo')}<p>Geschmack, der den Unterschied macht.</p></div><div><h2>Entdecken</h2><a href="/collections/all">Produkte</a><a href="/pages/rezepte">Rezepte & Ideen</a><a href="/pages/uber-uns">Über uns</a></div><div><h2>Zusammenarbeiten</h2><a href="/pages/geschaftskunden">Geschäftskunden</a><a href="/pages/private-label">Private Label</a><a href="/pages/contact">Kontakt</a></div><div><h2>Weiter</h2>${shop('Zum Shop','footer','footer-shop')}<a href="/policies/legal-notice">Impressum</a><a href="/policies/privacy-policy">Datenschutz</a></div></div><div class="shell footer-bottom"><span>© ${new Date().getFullYear()} Chelonaki · O-SOME TASTE</span><span>Be the Difference!</span></div></footer>`;
const layout = (title,description,body,cls='',canonical='') => `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><meta name="robots" content="noindex, nofollow"><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="${publicUrl('/images/logo.png') || '/images/logo.png'}">${canonical ? `<meta property="og:url" content="${esc(canonical)}"><link rel="canonical" href="${esc(canonical)}">` : ''}<link rel="icon" href="/images/favicon.png" type="image/png"><link rel="stylesheet" href="/styles.css"><script src="/motion.js" defer></script><title>${esc(title)} · O-SOME TASTE</title></head><body class="${cls}">${header()}<main id="inhalt" tabindex="-1">${body}</main>${footer()}</body></html>`;
async function page(path,title,description,body,cls='') { const file = path === '/' ? join(out,'index.html') : join(out,decodeURI(path.slice(1)),'index.html'); const canonical = publicUrl(path === '/' ? '/' : `${path}/`); await mkdir(dirname(file),{recursive:true}); await writeFile(file,prefixLocalUrls(layout(title,description,body,cls,canonical))); }
const card = p => `<article class="product-card reveal" style="--card-color:${p.color}"><a class="product-image" href="/products/${p.slug}">${img(p.image,`O-SOME TASTE Pesto ${p.name}`)}</a><div class="product-card-copy"><span class="eyebrow">O-SOME TASTE · Pesto</span><h3><a href="/products/${p.slug}">${esc(p.name)}</a></h3><p>${esc(p.description)}</p><div class="card-actions">${link(`/products/${p.slug}`,'Details')}${shop('Im Shop ansehen','product','shop-text')}</div></div></article>`;
const categoryVisual = c => c.image ? img(c.image,c.alt) : '<div class="aioli-art" aria-hidden="true"><span>Aioli</span><i></i></div>';

const home = `<section class="hero shell"><div class="hero-copy"><span class="eyebrow">Be the Difference! · O-SOME TASTE</span><h1>Geschmack, der den Unterschied macht.</h1><p>Pesto, Dressings und Aioli für alles, was du gerne auf den Tisch bringst. Entdecke O-SOME TASTE — und mach mehr aus dem nächsten Bissen.</p><div class="hero-actions">${shop('Zum Shop','hero','button button-dark')}${link('/collections/all','Produkte entdecken','button button-outline')}</div><p class="destination-note">Shop-Link: weiter zu chelonaki.eu</p></div><figure class="hero-art"><div class="hero-photo">${img('food-basilikum.webp','Pasta mit Basilikum und Tomaten','hero-food',true)}</div><div class="hero-orbit" aria-hidden="true"></div>${img('basilikum.webp','O-SOME TASTE Basilikum Pesto','hero-product',true)}<figcaption>Basilikum Pesto · eine Idee für deinen nächsten Teller</figcaption></figure></section>
<section class="proof-strip"><div class="shell"><span class="eyebrow">Aus der O-SOME-Geschichte</span><p><strong>Chili Pesto</strong> · Great Taste Award 2026</p><p><strong>Kalamata-Olive Pesto</strong> · Great Taste Award 2024</p></div></section>
<section class="section shell" id="geschmackswelten">${chapter('01','Geschmack','Ein Glas. Viele Möglichkeiten.')}<div class="category-grid">${categories.map((c,i)=>`<article class="category-card category-${i+1} reveal"><a href="${c.path}" class="category-image" aria-label="${c.name} entdecken">${categoryVisual(c)}</a><div class="category-text"><span class="eyebrow">${c.number} / Geschmackswelt</span><h3>${c.name}</h3><p>${c.copy}</p>${link(c.path,'Entdecken')}</div></article>`).join('')}</div></section>
<section class="feature-section"><div class="shell feature-grid"><div class="feature-media reveal"><span class="sun-dot" aria-hidden="true"></span>${img('chili-live.webp','O-SOME TASTE Chili Pesto','feature-product')}<small>Chili Pesto · O-SOME TASTE</small></div><div class="feature-copy reveal"><span class="eyebrow">02 / Im Fokus</span><h2>Ein bisschen Feuer. Viel Geschmack.</h2><p>Tomatenmark, Cashewkerne, Hartkäse und Chilischoten ergeben ein cremiges Pesto mit angenehmer Schärfe. Für Pasta, als Dip oder auf Brot.</p><p class="award-copy">Chili Pesto · Great Taste Award 2026</p><div class="stacked-actions">${link('/products/o-some-taste-pesto-chili','Mehr über dieses Pesto','button button-outline')}${shop('Im Shop ansehen','product','button button-dark')}</div></div></div></section>
<section class="philosophy"><div class="shell philosophy-grid"><div>${chapter('03','Haltung','Für Menschen, die gerne gut essen.')}<p>Wir mögen Essen, das im Gedächtnis bleibt. Deshalb steht bei O-SOME TASTE die Rezeptur im Mittelpunkt: wie Zutaten zusammenspielen, wie sich ein Produkt verwenden lässt — und wie daraus etwas wird, das man gerne teilt.</p>${link('/pages/uber-uns','Mehr über uns','button button-light')}</div><div class="philosophy-visual reveal">${img('food-zitrone.webp','Servieridee mit Zitrone und Kräutern')}</div></div></section>
<section class="section shell">${chapter('04','Ideen','Gute Ideen beginnen manchmal mit einem Glas.')}<div class="ideas-grid"><article class="idea-card reveal">${img('food-basilikum.webp','Pasta mit Basilikum Pesto')}<div><span class="eyebrow">Servieridee</span><h3>Basilikum auf Pasta</h3><p>Ein Teller Pasta, Basilikum Pesto und frische Tomaten.</p>${link('/products/o-some-taste-pesto-basilikum','Zum Pesto')}</div></article><article class="idea-card reveal">${img('food-zitrone.webp','Gericht mit Zitrone und Kräutern')}<div><span class="eyebrow">Servieridee</span><h3>Zitrone & Salbei</h3><p>Helle, kräuterige Aromen als Anregung für den nächsten Teller.</p>${link('/products/charibee-pesto-zitrone-salbei','Zum Pesto')}</div></article><article class="idea-card reveal">${img('food-steinpilz.webp','Herzhaftes Gericht mit Steinpilz')}<div><span class="eyebrow">Servieridee</span><h3>Steinpilz-Moment</h3><p>Ein herzhafter Akzent für Pasta und warme Gerichte.</p>${link('/products/o-some-taste-pesto-steinpilz','Zum Pesto')}</div></article></div><div class="section-outro">${link('/pages/rezepte','Alle Rezepte & Ideen','button button-outline')}</div></section>
<section class="people-section"><div class="shell people-grid"><div class="people-image reveal">${img('founder.webp','Eleftherios Samouladas mit O-SOME-Produkten')}</div><div class="people-copy reveal"><span class="eyebrow">05 / Menschen</span><h2>Guter Geschmack hat Menschen dahinter.</h2><p>Produktentwicklung, Markenideen und Vertrieb: Hinter O-SOME TASTE stehen Menschen, die unterschiedliche Erfahrungen an einen Tisch bringen.</p>${link('/pages/uber-uns','Lerne uns kennen','button button-outline')}</div></div></section>
<section class="section shell">${chapter('06','Für Unternehmen','Gute Ideen schmecken gemeinsam besser.')}<div class="business-grid"><article class="business-tile reveal"><span class="eyebrow">Handel · Feinkost · Gastronomie</span><h3>Mehr Geschmack für Ihr Sortiment.</h3><p>Entdecken Sie die O-SOME-Produkte für Ihr Geschäft und sprechen Sie mit uns über Ihre Anforderungen.</p>${link('/pages/geschaftskunden','Geschäftskunden','button button-outline')}</article><article class="business-tile business-tile-dark reveal"><span class="eyebrow">Private Label</span><h3>Ihre Idee. Ihr Produkt.</h3><p>Von der ersten Idee bis zur Umsetzung: gemeinsam entwickeln wir ein Lebensmittelprodukt mit Charakter.</p>${link('/pages/private-label','Private Label','button button-light')}</article></div></section>
<section class="closing"><div class="shell closing-inner"><span class="eyebrow">O-SOME TASTE</span><h2>Bereit für deinen nächsten Lieblingsgeschmack?</h2><div class="hero-actions">${shop('Zum Shop','footer','button button-dark')}${link('/pages/contact','Mit uns sprechen','button button-outline')}</div></div></section>`;

await rm(out,{recursive:true,force:true}); await mkdir(out,{recursive:true});
await cp(join(root,'public/images'),join(out,'images'),{recursive:true});
await cp(join(root,'src/styles.css'),join(out,'styles.css'));
await cp(join(root,'src/motion.js'),join(out,'motion.js'));
await page('/','Geschmack, der den Unterschied macht','O-SOME TASTE: Pesto, Dressings und Aioli entdecken. Eine Markenwelt für guten Geschmack und den nächsten Lieblingsbissen.',home,'home');

const catalogIntro = `<section class="page-hero shell"><span class="eyebrow">01 / Sortiment</span><h1>Geschmack entdecken.</h1><p>Von klassischem Basilikum bis würzigem Chili: Entdecke die Pesto-Welt von O-SOME TASTE. Weitere Geschmackswelten findest du in der Navigation.</p></section>`;
const categoryNav = `<nav class="category-nav shell" aria-label="Produktkategorien"><a href="/collections/all">Alle Produkte</a>${categories.map(c=>`<a href="${c.path}">${c.name}</a>`).join('')}</nav>`;
await page('/collections/all','Produkte entdecken','Der redaktionelle Überblick über Pesto und weitere Geschmackswelten von O-SOME TASTE.',`${catalogIntro}${categoryNav}<section class="section shell"><div class="product-grid">${products.map(card).join('')}</div></section><section class="section shell editorial-note"><h2>Noch mehr Geschmack</h2><p>Dressings und Aioli gehören zur O-SOME-Welt. Aktuell sind auf der bestehenden Website dafür keine Einzelprodukte gelistet. Entdecke die Geschmackswelten oder frag uns direkt.</p><div class="hero-actions">${link('/collections/dressing','Dressings')}${link('/collections/aioli','Aioli')}</div></section>`);
await page('/collections/pesto','Pesto entdecken','Sieben Pesto-Sorten von O-SOME TASTE redaktionell entdecken.',`<section class="page-hero shell"><span class="eyebrow">01 / Geschmack</span><h1>Pesto kann mehr als Pasta.</h1><p>Sieben Sorten, viele Ideen für deinen Tisch. Wähle deinen Geschmack und erfahre mehr über das Produkt.</p></section>${categoryNav}<section class="section shell"><div class="product-grid">${products.map(card).join('')}</div></section>`);
for (const c of categories.slice(1)) await page(c.path,`${c.name} entdecken`,`${c.name} als Geschmackswelt von O-SOME TASTE.`, `<section class="page-hero shell"><span class="eyebrow">${c.number} / Geschmackswelt</span><h1>${c.name}.</h1><p>${c.copy}</p></section>${categoryNav}<section class="section shell category-editorial"><div class="category-editorial-image">${categoryVisual(c)}</div><div><h2>Für neue Ideen am Tisch.</h2><p>${c.name === 'Dressings' ? 'Zwei Dressings sind auf der bisherigen Startseite dokumentiert, aktuell jedoch nicht in der Dressing-Kategorie gelistet. Hier findest du ihre Produktgeschichten ohne Preis- oder Verfügbarkeitsversprechen.' : 'Aioli gehört zur O-SOME-Welt. Auf der bisherigen Website sind derzeit keine einzelnen Aioli-Produkte gelistet. Für Fragen zum Sortiment erreichst du uns direkt.'}</p>${link('/pages/contact','Kontakt aufnehmen','button button-outline')}</div></section>${c.name === 'Dressings' ? `<section class="section shell"><h2>Aus dem O-SOME-Archiv</h2><div class="product-grid">${dressingArchive.map(p=>`<article class="product-card" style="--card-color:${p.color}"><a class="product-image" href="/products/${p.slug}">${img(p.image,`O-SOME TASTE Dressing ${p.name}`)}</a><div class="product-card-copy"><span class="eyebrow">Derzeit nicht gelistet</span><h3>${p.name}</h3><p>${p.description}</p>${link(`/products/${p.slug}`,'Details')}</div></article>`).join('')}</div></section>` : ''}`);

for (const p of products) await page(`/products/${p.slug}`,`Pesto ${p.name}`,`O-SOME TASTE Pesto ${p.name}: Geschmack, Ideen und Produktinformationen.`, `<nav class="breadcrumbs shell" aria-label="Breadcrumb"><a href="/">Start</a><span aria-hidden="true">/</span><a href="/collections/pesto">Pesto</a><span aria-hidden="true">/</span><span>${esc(p.name)}</span></nav><section class="product-detail shell"><div class="product-detail-image" style="--card-color:${p.color}">${img(p.image,`O-SOME TASTE Pesto ${p.name}`,'',true)}</div><div class="product-detail-copy"><span class="eyebrow">O-SOME TASTE · Pesto</span><h1>${esc(p.name)}.</h1><p class="lead">${esc(p.description)}</p><div class="detail-rule"></div><h2>Eine Idee für deinen Tisch</h2><p>Ob zu Pasta oder auf Brot: Dieses Pesto lädt dazu ein, den nächsten Teller nach deinem Geschmack zu gestalten.</p><div class="stacked-actions">${shop('Im Shop ansehen','product','button button-dark')}${link('/pages/rezepte','Rezepte & Ideen','button button-outline')}</div><p class="destination-note">Der Shop-Link führt zum gemeinsamen Chelonaki-Shopziel. Preise und Verfügbarkeit werden hier nicht angezeigt.</p></div></section><section class="section shell related-products">${chapter('02','Weiterprobieren','Noch mehr entdecken.')}<div class="product-grid">${products.filter(x=>x.slug!==p.slug).slice(0,3).map(card).join('')}</div></section>`);
for (const p of dressingArchive) await page(`/products/${p.slug}`,`Dressing ${p.name}`,`O-SOME TASTE Dressing ${p.name} aus dem Produktarchiv.`, `<nav class="breadcrumbs shell" aria-label="Breadcrumb"><a href="/">Start</a><span>/</span><a href="/collections/dressing">Dressings</a><span>/</span><span>${esc(p.name)}</span></nav><section class="product-detail shell"><div class="product-detail-image" style="--card-color:${p.color}">${img(p.image,`O-SOME TASTE Dressing ${p.name}`,'',true)}</div><div class="product-detail-copy"><span class="eyebrow">O-SOME TASTE · Dressing · Archiv</span><h1>${esc(p.name)}.</h1><p class="lead">${esc(p.description)}</p><p>Dieses Produkt ist auf der bisherigen O-SOME-Startseite verlinkt, aber derzeit nicht im Dressing-Katalog gelistet. Informationen zu aktuellen Produkten erhalten Sie direkt bei O-SOME.</p>${link('/pages/contact','Zum Kontakt','button button-outline')}</div></section>`);

await page('/pages/uber-uns','Über uns','Die Menschen und Ideen hinter O-SOME TASTE kennenlernen.',`<section class="page-hero shell"><span class="eyebrow">02 / Menschen</span><h1>Guter Geschmack hat Menschen dahinter.</h1><p>O-SOME TASTE verbindet Produktentwicklung, Markenideen und Vertrieb. Lernen Sie die Menschen kennen, die daran arbeiten.</p></section><section class="section shell about-grid"><div class="about-photo">${img('founder.webp','Eleftherios Samouladas mit O-SOME-Produkten')}</div><div><span class="eyebrow">Produktentwicklung</span><h2>Eleftherios Samouladas</h2><p>Eleftherios verantwortet die Produktentwicklung bei O-SOME TASTE. Sein Hintergrund als Koch und Ernährungswissenschaftler prägt die Arbeit an den Rezepturen.</p>${link('/collections/all','Produkte entdecken','button button-outline')}</div></section><section class="section shell team-list">${chapter('03','Team','Verschiedene Perspektiven. Ein Geschmack.')}<div><article><h3>Georgios Samouladas</h3><p>Marketing und Markenkommunikation</p></article><article><h3>Lars Wuttke</h3><p>Vertrieb und Geschäftskunden</p></article></div></section>`);
await page('/pages/geschaftskunden','Geschäftskunden','O-SOME TASTE für Handel, Feinkost und Gastronomie.',`<section class="page-hero shell"><span class="eyebrow">03 / Zusammenarbeit</span><h1>Mehr Geschmack für Ihr Sortiment.</h1><p>Ob Handel, Feinkost oder Gastronomie: Wir sprechen mit Ihnen über passende Produkte und Ihre Anforderungen.</p></section><section class="section shell"><div class="business-grid"><article class="business-tile"><span class="eyebrow">01 / Sortiment</span><h2>Produkte kennenlernen</h2><p>Entdecken Sie die aktuellen O-SOME-Pestos und ihre Einsatzmöglichkeiten.</p>${link('/collections/all','Sortiment ansehen')}</article><article class="business-tile business-tile-dark"><span class="eyebrow">02 / Austausch</span><h2>Gemeinsam planen</h2><p>Schildern Sie uns, welche Produkte und Anwendungsfelder für Ihr Geschäft interessant sind.</p><a class="button button-light" href="mailto:${CONTACT_EMAIL}?subject=Gesch%C3%A4ftskundenanfrage%20O-SOME%20TASTE">Geschäftskundenanfrage</a></article></div></section><section class="section shell editorial-note"><h2>Ein guter Anfang: ein Gespräch.</h2><p>Schreiben Sie an <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a> oder rufen Sie uns an.</p></section>`);
await page('/pages/private-label','Private Label','Private-Label-Produktentwicklung mit O-SOME TASTE besprechen.',`<section class="page-hero shell"><span class="eyebrow">04 / Ihre Idee</span><h1>Aus Ihrer Idee wird ein Produkt mit Charakter.</h1><p>O-SOME TASTE begleitet Lebensmittelideen von der ersten Überlegung bis zur Umsetzung. Leistungen und Umfang klären wir passend zu Ihrem Vorhaben.</p></section><section class="section shell">${chapter('01','Prozess','Schritt für Schritt zum eigenen Produkt.')}<ol class="process-list"><li><span>01</span><div><h3>Idee & Ziel</h3><p>Wir besprechen Zielgruppe, Geschmack und Anforderungen.</p></div></li><li><span>02</span><div><h3>Rezepturentwicklung</h3><p>Aus der Idee entsteht eine Rezeptur, die abgestimmt und getestet wird.</p></div></li><li><span>03</span><div><h3>Abstimmung</h3><p>Prototyp und weitere Schritte werden gemeinsam besprochen.</p></div></li><li><span>04</span><div><h3>Umsetzung</h3><p>Je nach Projekt können Sourcing, Produktion und Vermarktung Teil der Zusammenarbeit sein.</p></div></li></ol></section><section class="closing"><div class="shell closing-inner"><h2>Reden wir über Ihre Idee.</h2><a class="button button-dark" href="mailto:${CONTACT_EMAIL}?subject=Private-Label-Projekt%20O-SOME%20TASTE">Private-Label-Projekt besprechen</a></div></section>`);
await page('/pages/contact','Kontakt','O-SOME TASTE per E-Mail oder Telefon kontaktieren.',`<section class="page-hero shell"><span class="eyebrow">05 / Kontakt</span><h1>Schreiben wir die nächste Idee zusammen.</h1><p>Für Produktfragen, Geschäftskunden und Private Label erreichen Sie uns direkt. Wir freuen uns auf Ihre Nachricht.</p></section><section class="section shell contact-grid"><div><h2>Kontakt aufnehmen</h2><p>Nutzen Sie Ihre E-Mail-App oder kopieren Sie die Adresse. Ein Versand erfolgt erst durch Ihre E-Mail-Anwendung.</p><a class="contact-address" href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a><a class="contact-address" href="tel:+491712997495">${CONTACT_PHONE}</a><div class="hero-actions"><a class="button button-dark" href="mailto:${CONTACT_EMAIL}">E-Mail schreiben</a><a class="button button-outline" href="tel:+491712997495">Anrufen</a></div></div><div class="contact-aside"><span class="eyebrow">Betrieben von Chelonaki</span><p>Eleftherios Samouladas<br>Zeppelinstraße 7<br>68519 Viernheim</p></div></section>`);
const recipeIndex = `<section class="page-hero shell"><span class="eyebrow">06 / Inspiration</span><h1>Gute Ideen beginnen manchmal mit einem Glas.</h1><p>Servierideen und vorhandene Beiträge aus der O-SOME-Welt. Für den nächsten Teller, den du gern teilst.</p></section><section class="section shell"><div class="ideas-grid"><article class="idea-card">${img('food-basilikum.webp','Pasta mit Basilikum Pesto')}<div><span class="eyebrow">Servieridee</span><h2>Basilikum auf Pasta</h2><p>Ein Teller Pasta, Basilikum Pesto und frische Tomaten.</p>${link('/products/o-some-taste-pesto-basilikum','Zum Produkt')}</div></article><article class="idea-card">${img('food-zitrone.webp','Gericht mit Zitrone und Kräutern')}<div><span class="eyebrow">Servieridee</span><h2>Zitrone & Salbei</h2><p>Helle, kräuterige Aromen für neue Tellerideen.</p>${link('/products/charibee-pesto-zitrone-salbei','Zum Produkt')}</div></article><article class="idea-card idea-type"><div><span class="eyebrow">Aus dem O-SOME-Archiv</span><h2>Moussaka</h2><p>Ein vorhandener Beitrag mit Zutatenidee für den griechischen Klassiker.</p>${link(`${RECIPE_SLUG}/`,'Beitrag lesen')}</div></article></div></section>`;
await page('/pages/rezepte','Rezepte & Ideen','Servierideen und vorhandene Beiträge von O-SOME TASTE.',recipeIndex);
await page('/blogs/rezepte','Rezepte im Archiv','Die Rezeptbeiträge von O-SOME TASTE.',recipeIndex);
await page(RECIPE_SLUG,'Moussaka – Rezeptidee','Moussaka-Beitrag aus dem O-SOME-TASTE-Archiv.',`<nav class="breadcrumbs shell" aria-label="Breadcrumb"><a href="/">Start</a><span>/</span><a href="/pages/rezepte">Rezepte & Ideen</a></nav><article class="section shell recipe-article"><span class="eyebrow">Aus dem O-SOME-Archiv · 26. Juli 2025</span><h1>Moussaka. Herzhaft griechisch genießen.</h1><p class="lead">Ein vorhandener O-SOME-Beitrag über den griechischen Klassiker. Der Originaltext nennt Zutaten, aber keine vollständige Zubereitung; deshalb ist dies eine Anregung und kein vollständiges Rezept.</p><h2>Im Originalbeitrag genannt</h2><ul><li>Auberginen</li><li>Hackfleisch oder vegetarische Alternative</li><li>Zwiebeln und Knoblauch</li><li>Olivenöl</li><li>Béchamelsauce</li><li>Salz und Pfeffer</li></ul>${link('/pages/rezepte','Weitere Ideen','button button-outline')}</article>`);
await page('/policies/legal-notice','Impressum','Impressum von Chelonaki für O-SOME TASTE.',`<section class="section shell legal-copy"><span class="eyebrow">Rechtliches</span><h1>Impressum</h1><p>Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG)</p><p><strong>Chelonaki</strong><br>Inhaber: Eleftherios Samouladas<br>Zeppelinstraße 7<br>68519 Viernheim<br>Deutschland</p><p>Rechtsform: Einzelunternehmen</p><p>Telefon: <a href="tel:+491712997495">+49 171 2997495</a><br>E-Mail: <a href="mailto:info@chelonaki.eu">info@chelonaki.eu</a></p><p>Kontakt zur Marke O-SOME TASTE: <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a></p><h2>Verbraucherstreitbeilegung</h2><p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p></section>`);
await page('/policies/privacy-policy','Datenschutz','Datenschutzhinweise für die statische O-SOME-TASTE-Website.',`<section class="section shell legal-copy"><span class="eyebrow">Rechtliches</span><h1>Datenschutz</h1><p>Stand: 23. September 2026. Diese Hinweise gelten für diese O-SOME-TASTE-Markenwebsite auf GitHub Pages.</p><h2>Verantwortlicher</h2><p>Eleftherios Samouladas, handelnd unter Chelonaki<br>Zeppelinstraße 7<br>68519 Viernheim, Deutschland<br>Telefon: <a href="tel:+491712997495">+49 171 2997495</a><br>E-Mail: <a href="mailto:info@chelonaki.eu">info@chelonaki.eu</a></p><h2>Bereitstellung der Website</h2><p>Diese statische Website wird über GitHub Pages bereitgestellt. Beim Aufruf verarbeitet der Hostinganbieter technisch erforderliche Verbindungsdaten. Nach <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages">Angaben von GitHub</a> werden IP-Adressen von Besuchern zu Sicherheitszwecken protokolliert und gespeichert. Weitere Informationen enthält die <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">Datenschutzerklärung von GitHub</a>. Die Bereitstellung der Website und ihre Sicherheit beruhen auf unserem berechtigten Interesse gemäß Art. 6 Abs. 1 lit. f DSGVO.</p><h2>Cookies und Analyse</h2><p>Der eigene Code dieser Website setzt keine Analyse- oder Marketing-Cookies ein. Es sind keine Analysewerkzeuge, Werbepixel, eingebetteten Inhalte oder externen Schriften eingebunden.</p><h2>Kontaktaufnahme</h2><p>Diese Website enthält kein Kontaktformular. Beim Klick auf einen E-Mail- oder Telefonlink wird Ihre eigene Anwendung geöffnet. Wenn Sie uns über <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a> oder telefonisch kontaktieren, verarbeiten wir die von Ihnen übermittelten Angaben zur Bearbeitung Ihrer Anfrage. Bei vertragsbezogenen Anfragen ist Art. 6 Abs. 1 lit. b DSGVO die Grundlage; sonst Art. 6 Abs. 1 lit. f DSGVO. Wir löschen die Daten, wenn die Anfrage abgeschlossen ist und keine gesetzlichen Aufbewahrungspflichten oder berechtigten Interessen mehr bestehen.</p><h2>Externer Shop-Link</h2><p>Shop-Links führen erst nach Ihrer Aktivierung zu <a href="${SHOP_URL}">${SHOP_URL}</a>. Für die Verarbeitung auf der externen Chelonaki-Seite gelten deren <a href="https://www.chelonaki.eu/datenschutz/">Datenschutzhinweise</a>. Auf dieser Markenwebsite finden keine Bestellungen statt.</p><h2>Ihre Rechte</h2><p>Sie haben im Rahmen der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen. Wenden Sie sich dazu an <a href="mailto:info@chelonaki.eu">info@chelonaki.eu</a>. Sie können sich außerdem bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere beim Hessischen Beauftragten für Datenschutz und Informationsfreiheit.</p></section>`);
await writeFile(join(out,'404.html'),prefixLocalUrls(layout('Seite nicht gefunden','Diese Seite wurde nicht gefunden.',`<section class="page-hero shell"><span class="eyebrow">404 / Nicht gefunden</span><h1>Hier führt der Weg nicht weiter.</h1><p>Vielleicht findest du den gesuchten Geschmack an anderer Stelle.</p><div class="hero-actions">${link('/collections/all','Produkte entdecken','button button-dark')}${link('/','Zur Startseite','button button-outline')}</div></section>`)));
console.log(`Built ${products.length} product pages and core editorial routes in ${out}`);
